# Generated by Django 4.2.6 on 2024-04-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='authors',
        ),
    ]
