# Generated by Django 4.2.6 on 2024-04-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_board_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='alias',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
