# Generated by Django 4.2.6 on 2024-04-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_task_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='alias',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
